# argocd-app-dev.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Dommys/Dev-Environment.git
    targetRevision: dev           # or the exact branch name (e.g., master)
    path: dev-app-chart            # <— THIS is the chart folder
    helm:
      valueFiles:
        - values.dev.yaml          # relative to the chart path above
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

