image:
  repository: dev-app
  tag: dev
  pullPolicy: IfNotPresent

replicaCount: 1

container:
  port: 5173

service:
  type: ClusterIP
  port: 5173

# Optional: improve file watching in k8s
env:
  - name: CHOKIDAR_USEPOLLING
    value: "true"
  - name: CHOKIDAR_INTERVAL
    value: "250"

ingress:
  enabled: false

