image:
  repository: bestiee/vue-app
  tag: "f4f4276608e50daec3e3a74caa7d63b72e56d331"
  pullPolicy: IfNotPresent

replicaCount: 2

container:
  port: 80

service:
  type: LoadBalancer     # matches your prod style
  port: 80

ingress:
  enabled: false         # or enable + set a real host if you prefer Ingress

