apiVersion: v1
kind: Service
metadata:
  name: {{ include "dev-app-chart.fullname" . }}
  labels:
    {{- include "dev-app-chart.labels" . | nindent 4 }}
spec:
  type: {{ default "ClusterIP" .Values.service.type }}
  ports:
    - name: http
      port: {{ default 80 .Values.service.port }}
      targetPort: {{ default 80 .Values.container.port }}
      protocol: TCP
    {{- range .Values.service.extraPorts }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ default .port .targetPort }}
      protocol: {{ default "TCP" .protocol }}
    {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "dev-app-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}


