apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vue-app
  template:
    metadata:
      labels:
        app: vue-app
    spec:
      containers:
        - name: vue-app
          # Build this image locally with your Dockerfile.dev (name/tag matches below)
          image: dev-app:dev
          imagePullPolicy: IfNotPresent
          # If your Dockerfile.dev already runs `npm run dev -- --host --port 5173`,
          # you can omit the command/args. Otherwise, uncomment the next two lines:
          # command: ["npm"]
          # args: ["run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]
          env:
            - name: NODE_ENV
              value: development
          ports:
            - containerPort: 5173
---
apiVersion: v1
kind: Service
metadata:
  name: vue-app-service
spec:
  selector:
    app: vue-app
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
  type: ClusterIP

