apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-app
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: vue-app
          image: dev-app:dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5173
          # If Dockerfile.dev doesn’t already run vite, uncomment:
          # command: ["npm"]
          # args: ["run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]
---
apiVersion: v1
kind: Service
metadata:
  name: vue-app-service
spec:
  type: ClusterIP
  ports:
    - port: 5173
      targetPort: 5173

